import { TrainingAdjustments } from "../types/training";

// Domyślne ustawienia
export const defaultAdjustments: TrainingAdjustments = {
  speed: 1.0,
  variation: 0,
  disappearingProbability: 0.3,
  trainingArea: {
    aspectRatio: 9 / 16,
    margin: 40,
    overlayOpacity: 0.5,
    upperZoneRatio: 0.66,
    targetSize: 30,
    hitRadius: 30,
  },
  defaultBehavior: {
    type: 'static',
    followThreshold: 3000,
    minFollowDistance: 2000,
  },
  enabledKeypoints: {
    leftWrist: true,
    rightWrist: true,
    leftAnkle: true,
    rightAnkle: true,
  },
  //   keypointProbabilities: {
  //     leftWrist: 0.25,
  //     rightWrist: 0.25,
  //     leftAnkle: 0.25,
  //     rightAnkle: 0.25,
  //   },
  targetProbabilities: {
    handPair: 0.2,
    handSingle: 0.15,
    singleLeftWrist: 0.25,
    singleRightWrist: 0.25,
    singleLeftAnkle: 0.25,
    singleRightAnkle: 0.25,
    anyHand: 0.1,
    anyFoot: 0.05,
    footSingle: 0.05,
    anyLimb: 0.05,
    sequence: 0.2,
    follow: 0.2,
  },
  sequenceConfig: {
    minSequenceSize: 2,
    maxSequenceSize: 5,
    minDelay: 500,
    maxDelay: 2000,
    enforceOrder: true,
    showNumbers: true,
    handProbability: 0.7,
    pairProbability: 0.3,
    footMinDelay: 1000,
    footMaxDelay: 2000,
    delayBetweenTargets: 500,
  },
  followConfig: {
    minDuration: 2000,
    maxDuration: 5000,
    minRadius: 1000,
    maxRadius: 5000,
    circleProbability: 0.6,
    showPath: true,
    pathOpacity: 0.4,
    segments: {
      path: 16,
      circle: 24,
      line: 2,
    },
  },
  disappearingConfig: {
    minDuration: 2000,
    maxDuration: 5000,
    sequenceBuffer: 1000,
    probabilities: {
      sequence: 0.3,
      follow: 0.2,
      handPair: 0.3,
      singleHand: 0.4,
      anyHand: 0.4,
      anyFoot: 0.3,
      anyLimb: 0.3,
      singleFoot: 0.3,
    },
  },
};