import { 
    PredefinedTraining
  } from '../types/training';

// Predefiniowane treningi
export const predefinedTrainings: PredefinedTraining[] = [
    {
      id: 'full-body-basic',
      name: 'Trening całego ciała - podstawowy',
      description: 'Podstawowy trening angażujący wszystkie kończyny, idealny na początek.',
      category: 'full',
      imageUrl: '/assets/trainings/functional.png',
      config: {
        // Domyślna konfiguracja dla treningu całego ciała
        speed: 1.0,
        trainingArea: {
            aspectRatio: 9/16,
            margin: 40,
            overlayOpacity: 0.5,
            upperZoneRatio: 0.66,
            targetSize: 30,
            hitRadius: 30,
        },
        variation: 0,
        disappearingProbability: 0.3,
        defaultBehavior: {
          type: "static",
          minFollowDistance: 2000,
          followThreshold: 3000,
        },
        enabledKeypoints: {
            leftWrist: true,
            rightWrist: true,
            leftAnkle: true,
            rightAnkle: true,
        },
        disappearingConfig: {
            minDuration: 2000,
            maxDuration: 6000,
            sequenceBuffer: 1000,
        },
        targetProbabilities: {
          singleLeftWrist: 0.25,
          singleRightWrist: 0.25,
          singleLeftAnkle: 0.25,
          singleRightAnkle: 0.25,
          anyHand: 0.3,
          anyFoot: 0.2,
          anyLimb: 0.3,
          sequence: 0,
          follow: 0,
          handPair: 0.2,
        },
        followConfig: {
            minDuration: 2000,
            maxDuration: 5000,
            minRadius: 90,
            maxRadius: 240,
            circleProbability: 0.5,
            showPath: true,
            pathOpacity: 0.5,
            segments: {
                path: 16,
                circle: 24,
                line: 2,
            },
        },
        sequenceConfig: {
            minSequenceSize: 2,
            maxSequenceSize: 5,
            delayBetweenTargets: 500,
            handProbability: 0.5,
            pairProbability: 0.5,
            footMinDelay: 1000,
            footMaxDelay: 3000,
            minDelay: 500,
            maxDelay: 2000,
            enforceOrder: true,
            showNumbers: true,
        },
      }
    },
    {
      id: 'upper-body-intense',
      name: 'Intensywny trening górnych partii',
      description: 'Szybki trening skupiający się na koordynacji rąk.',
      category: 'upper',
      imageUrl: '/assets/trainings/upper.png',
      config: {
        speed: 1.4,
        trainingArea: {
          aspectRatio: 9/16,
          margin: 35,
          overlayOpacity: 0.4,
          upperZoneRatio: 0.8,
          targetSize: 25,
          hitRadius: 25,
        },
        variation: 0.2,
        disappearingProbability: 0.4,
        defaultBehavior: {
          type: "static",
          minFollowDistance: 1500,
          followThreshold: 2500,
        },
        enabledKeypoints: {
          leftWrist: true,
          rightWrist: true,
          leftAnkle: false,
          rightAnkle: false,
        },
        disappearingConfig: {
          minDuration: 1500,
          maxDuration: 4000,
          sequenceBuffer: 800,
          probabilities: {
            sequence: 0.4,
            follow: 0.6,
            handPair: 0.3,
            singleHand: 0.4,
            anyHand: 0.3,
            anyFoot: 0,
            anyLimb: 0,
            singleFoot: 0,
          },
        },
        targetProbabilities: {
          singleLeftWrist: 0.5,
          singleRightWrist: 0.5,
          singleLeftAnkle: 0,
          singleRightAnkle: 0,
          anyHand: 0.3,
          anyFoot: 0,
          anyLimb: 0,
          sequence: 0.2,
          follow: 0.2,
          handPair: 0.3,
        },
        followConfig: {
          minDuration: 1500,
          maxDuration: 4000,
          minRadius: 70,
          maxRadius: 200,
          circleProbability: 0.6,
          showPath: true,
          pathOpacity: 0.4,
          segments: {
            path: 20,
            circle: 32,
            line: 2,
          },
        },
        sequenceConfig: {
          minSequenceSize: 3,
          maxSequenceSize: 6,
          delayBetweenTargets: 400,
          handProbability: 1.0,
          pairProbability: 0.3,
          footMinDelay: 0,
          footMaxDelay: 0,
          minDelay: 400,
          maxDelay: 1500,
          enforceOrder: true,
          showNumbers: true,
        },
      }
    },
    {
      id: 'lower-body-precision',
      name: 'Trening precyzji nóg',
      description: 'Trening skupiający się na precyzyjnych ruchach nóg.',
      category: 'lower',
      imageUrl: '/assets/trainings/lower.png',
      config: {
        speed: 0.8,
        trainingArea: {
          aspectRatio: 9/16,
          margin: 45,
          overlayOpacity: 0.5,
          upperZoneRatio: 0.4,
          targetSize: 35,
          hitRadius: 40,
        },
        variation: 0.1,
        disappearingProbability: 0.2,
        defaultBehavior: {
          type: "static",
          minFollowDistance: 2500,
          followThreshold: 3500,
        },
        enabledKeypoints: {
          leftWrist: false,
          rightWrist: false,
          leftAnkle: true,
          rightAnkle: true,
        },
        disappearingConfig: {
          minDuration: 2500,
          maxDuration: 7000,
          sequenceBuffer: 1200,
          probabilities: {
            sequence: 0.2,
            follow: 0.4,
            handPair: 0,
            singleHand: 0,
            anyHand: 0,
            anyFoot: 0.4,
            anyLimb: 0,
            singleFoot: 0.4,
          },
        },
        targetProbabilities: {
          singleLeftWrist: 0,
          singleRightWrist: 0,
          singleLeftAnkle: 0.5,
          singleRightAnkle: 0.5,
          anyHand: 0,
          anyFoot: 0.4,
          anyLimb: 0,
          sequence: 0.3,
          follow: 0.3,
          handPair: 0,
        },
        followConfig: {
          minDuration: 3000,
          maxDuration: 6000,
          minRadius: 100,
          maxRadius: 250,
          circleProbability: 0.4,
          showPath: true,
          pathOpacity: 0.6,
          segments: {
            path: 12,
            circle: 20,
            line: 2,
          },
        },
        sequenceConfig: {
          minSequenceSize: 2,
          maxSequenceSize: 4,
          delayBetweenTargets: 800,
          handProbability: 0,
          pairProbability: 0.2,
          footMinDelay: 1500,
          footMaxDelay: 4000,
          minDelay: 1000,
          maxDelay: 3000,
          enforceOrder: true,
          showNumbers: true,
        },
      }
    },
    {
      id: 'random-training',
      name: 'Trening losowy',
      description: 'Pełna losowość celów i sekwencji dla maksymalnej różnorodności.',
      category: 'random',
      imageUrl: '/assets/trainings/random.png',
      config: {
        speed: 1.2,
        trainingArea: {
          aspectRatio: 9/16,
          margin: 35,
          overlayOpacity: 0.45,
          upperZoneRatio: 0.6,
          targetSize: 30,
          hitRadius: 35,
        },
        variation: 0.4,
        disappearingProbability: 0.5,
        defaultBehavior: {
          type: "static",
          minFollowDistance: 2000,
          followThreshold: 3000,
        },
        enabledKeypoints: {
          leftWrist: true,
          rightWrist: true,
          leftAnkle: true,
          rightAnkle: true,
        },
        disappearingConfig: {
          minDuration: 2000,
          maxDuration: 5000,
          sequenceBuffer: 1000,
          probabilities: {
            sequence: 0.5,
            follow: 0.5,
            handPair: 0.5,
            singleHand: 0.5,
            anyHand: 0.5,
            anyFoot: 0.5,
            anyLimb: 0.5,
            singleFoot: 0.5,
          },
        },
        targetProbabilities: {
          singleLeftWrist: 0.25,
          singleRightWrist: 0.25,
          singleLeftAnkle: 0.25,
          singleRightAnkle: 0.25,
          anyHand: 0.2,
          anyFoot: 0.2,
          anyLimb: 0.2,
          sequence: 0.1,
          follow: 0.2,
          handPair: 0.1,
        },
        followConfig: {
          minDuration: 2000,
          maxDuration: 5000,
          minRadius: 80,
          maxRadius: 220,
          circleProbability: 0.5,
          showPath: true,
          pathOpacity: 0.5,
          segments: {
            path: 16,
            circle: 24,
            line: 2,
          },
        },
        sequenceConfig: {
          minSequenceSize: 2,
          maxSequenceSize: 6,
          delayBetweenTargets: 600,
          handProbability: 0.5,
          pairProbability: 0.5,
          footMinDelay: 1000,
          footMaxDelay: 3000,
          minDelay: 500,
          maxDelay: 2500,
          enforceOrder: false,
          showNumbers: true,
        },
      }
    },
    {
      id: 'basic-hands',
      name: 'Podstawowy trening rąk',
      description: 'Spokojny trening koordynacji ruchów rąk, idealny do nauki.',
      category: 'upper',
      imageUrl: '/assets/trainings/hands.png',
      config: {
        speed: 1.0,
        trainingArea: {
          aspectRatio: 9/16,
          margin: 40,
          overlayOpacity: 0.5,
          upperZoneRatio: 0.8,
          targetSize: 35,
          hitRadius: 40,
        },
        variation: 0,
        disappearingProbability: 0.1,
        defaultBehavior: {
          type: "static",
          minFollowDistance: 2000,
          followThreshold: 3000,
        },
        enabledKeypoints: {
          leftWrist: true,
          rightWrist: true,
          leftAnkle: false,
          rightAnkle: false,
        },
        disappearingConfig: {
          minDuration: 3000,
          maxDuration: 6000,
          sequenceBuffer: 1500,
          probabilities: {
            sequence: 0.1,
            follow: 0.1,
            handPair: 0.1,
            singleHand: 0.1,
            anyHand: 0.1,
            anyFoot: 0,
            anyLimb: 0,
            singleFoot: 0,
          },
        },
        targetProbabilities: {
          singleLeftWrist: 0.4,
          singleRightWrist: 0.4,
          singleLeftAnkle: 0,
          singleRightAnkle: 0,
          anyHand: 0.1,
          anyFoot: 0,
          anyLimb: 0,
          sequence: 0.05,
          follow: 0.05,
          handPair: 0.2,
        },
        followConfig: {
          minDuration: 3000,
          maxDuration: 6000,
          minRadius: 100,
          maxRadius: 200,
          circleProbability: 0.3,
          showPath: true,
          pathOpacity: 0.6,
          segments: {
            path: 12,
            circle: 16,
            line: 2,
          },
        },
        sequenceConfig: {
          minSequenceSize: 2,
          maxSequenceSize: 3,
          delayBetweenTargets: 800,
          handProbability: 1.0,
          pairProbability: 0.2,
          footMinDelay: 0,
          footMaxDelay: 0,
          minDelay: 800,
          maxDelay: 2000,
          enforceOrder: true,
          showNumbers: true,
        },
      }
    },
    {
      id: 'basic-feet',
      name: 'Podstawowy trening nóg',
      description: 'Spokojny trening koordynacji ruchów nóg, idealny do nauki.',
      category: 'lower',
      imageUrl: '/assets/trainings/feet.png',
      config: {
        speed: 0.9,
        trainingArea: {
          aspectRatio: 9/16,
          margin: 45,
          overlayOpacity: 0.5,
          upperZoneRatio: 0.3,
          targetSize: 40,
          hitRadius: 45,
        },
        variation: 0,
        disappearingProbability: 0.1,
        defaultBehavior: {
          type: "static",
          minFollowDistance: 2500,
          followThreshold: 3500,
        },
        enabledKeypoints: {
          leftWrist: false,
          rightWrist: false,
          leftAnkle: true,
          rightAnkle: true,
        },
        disappearingConfig: {
          minDuration: 3500,
          maxDuration: 7000,
          sequenceBuffer: 2000,
          probabilities: {
            sequence: 0.1,
            follow: 0.1,
            handPair: 0,
            singleHand: 0,
            anyHand: 0,
            anyFoot: 0.1,
            anyLimb: 0,
            singleFoot: 0.1,
          },
        },
        targetProbabilities: {
          singleLeftWrist: 0,
          singleRightWrist: 0,
          singleLeftAnkle: 0.4,
          singleRightAnkle: 0.4,
          anyHand: 0,
          anyFoot: 0.2,
          anyLimb: 0,
          sequence: 0.05,
          follow: 0.05,
          handPair: 0,
        },
        followConfig: {
          minDuration: 4000,
          maxDuration: 8000,
          minRadius: 120,
          maxRadius: 250,
          circleProbability: 0.3,
          showPath: true,
          pathOpacity: 0.7,
          segments: {
            path: 10,
            circle: 16,
            line: 2,
          },
        },
        sequenceConfig: {
          minSequenceSize: 2,
          maxSequenceSize: 3,
          delayBetweenTargets: 1200,
          handProbability: 0,
          pairProbability: 0.2,
          footMinDelay: 1500,
          footMaxDelay: 4000,
          minDelay: 1500,
          maxDelay: 3500,
          enforceOrder: true,
          showNumbers: true,
        },
      }
    },
    {
      id: 'sequence-only',
      name: 'Trening sekwencyjny',
      description: 'Trening skupiający się na zapamiętywaniu i wykonywaniu sekwencji ruchów.',
      category: 'full',
      imageUrl: '/assets/trainings/sequence.png',
      config: {
        speed: 1.0,
        trainingArea: {
          aspectRatio: 9/16,
          margin: 40,
          overlayOpacity: 0.5,
          upperZoneRatio: 0.66,
          targetSize: 35,
          hitRadius: 40,
        },
        variation: 0.1,
        disappearingProbability: 0.3,
        defaultBehavior: {
          type: "static",
          minFollowDistance: 2000,
          followThreshold: 3000,
        },
        enabledKeypoints: {
          leftWrist: true,
          rightWrist: true,
          leftAnkle: true,
          rightAnkle: true,
        },
        disappearingConfig: {
          minDuration: 2500,
          maxDuration: 5000,
          sequenceBuffer: 1500,
          probabilities: {
            sequence: 0.8,
            follow: 0,
            handPair: 0.2,
            singleHand: 0.2,
            anyHand: 0.2,
            anyFoot: 0.2,
            anyLimb: 0.2,
            singleFoot: 0.2,
          },
        },
        targetProbabilities: {
          singleLeftWrist: 0.1,
          singleRightWrist: 0.1,
          singleLeftAnkle: 0.1,
          singleRightAnkle: 0.1,
          anyHand: 0.1,
          anyFoot: 0.1,
          anyLimb: 0.1,
          sequence: 0.8,
          follow: 0,
          handPair: 0.2,
        },
        followConfig: {
          minDuration: 0,
          maxDuration: 0,
          minRadius: 0,
          maxRadius: 0,
          circleProbability: 0,
          showPath: false,
          pathOpacity: 0,
          segments: {
            path: 0,
            circle: 0,
            line: 0,
          },
        },
        sequenceConfig: {
          minSequenceSize: 3,
          maxSequenceSize: 7,
          delayBetweenTargets: 600,
          handProbability: 0.6,
          pairProbability: 0.3,
          footMinDelay: 1200,
          footMaxDelay: 3000,
          minDelay: 600,
          maxDelay: 2000,
          enforceOrder: true,
          showNumbers: true,
        },
      }
    },
    {
      id: 'follow-only',
      name: 'Trening śledzenia',
      description: 'Trening skupiający się na płynnym śledzeniu celów w ruchu.',
      category: 'full',
      imageUrl: '/assets/trainings/follow.png',
      config: {
        speed: 1.0,
        trainingArea: {
          aspectRatio: 9/16,
          margin: 40,
          overlayOpacity: 0.5,
          upperZoneRatio: 0.66,
          targetSize: 35,
          hitRadius: 40,
        },
        variation: 0.2,
        disappearingProbability: 0.2,
        defaultBehavior: {
          type: "follow",
          minFollowDistance: 1500,
          followThreshold: 2500,
        },
        enabledKeypoints: {
          leftWrist: true,
          rightWrist: true,
          leftAnkle: true,
          rightAnkle: true,
        },
        disappearingConfig: {
          minDuration: 2000,
          maxDuration: 4000,
          sequenceBuffer: 1000,
          probabilities: {
            sequence: 0,
            follow: 0.8,
            handPair: 0.2,
            singleHand: 0.2,
            anyHand: 0.2,
            anyFoot: 0.2,
            anyLimb: 0.2,
            singleFoot: 0.2,
          },
        },
        targetProbabilities: {
          singleLeftWrist: 0.1,
          singleRightWrist: 0.1,
          singleLeftAnkle: 0.1,
          singleRightAnkle: 0.1,
          anyHand: 0.1,
          anyFoot: 0.1,
          anyLimb: 0.1,
          sequence: 0,
          follow: 0.8,
          handPair: 0.2,
        },
        followConfig: {
          minDuration: 2500,
          maxDuration: 6000,
          minRadius: 80,
          maxRadius: 200,
          circleProbability: 0.6,
          showPath: true,
          pathOpacity: 0.6,
          segments: {
            path: 20,
            circle: 32,
            line: 4,
          },
        },
        sequenceConfig: {
          minSequenceSize: 0,
          maxSequenceSize: 0,
          delayBetweenTargets: 0,
          handProbability: 0,
          pairProbability: 0,
          footMinDelay: 0,
          footMaxDelay: 0,
          minDelay: 0,
          maxDelay: 0,
          enforceOrder: false,
          showNumbers: false,
        },
      }
    }
  ];